# Generated by Django 5.2 on 2025-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=jNQXAC9IVRw'),
        ),
    ]
